##########################################
# 站点配置

baseURL = "https://raycoder.me/"
title = "Ray's Blog"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
hasCJKLanguage = true

# 主题选择
theme = ["hugo-notice", "tony"]

# `hugo new` 新建文章自动打开的文本编辑器
newContentEditor = "D:/Typora/Typora.exe"

# 摘要的字数限制
summaryLength = 235

# 是否开启 GitHub 风格的 Emoji 书写方式
enableEmoji = true

# 每一分页的文章数
paginate = 15

# 作者信息
[author]
    # 名字
    name = "Ray"
    # 邮箱
    email = "ray@raycoder.me"
    # 座右铭或简介
    motto = "夜晚再黑，也压不过雪的白。"
    # 头像
    avatar = "https://cdn.jsdelivr.net/gh/FFRaycoder/cdn/imgs/20200509175006.png"
    # 网站（默认值：baseURL）
    website = "https://themetony.github.io/hugo-theme-tony/"
    # GitHub
    github = "https://github.com/FFRaycoder/"

# URL 结构
[permalinks]
    categories = "/categories/:slug/"
    tags = "/tags/:slug/"

# 页面分类
[taxonomies]
  category = "categories"
  tag = "tags"

##########################################
# 菜单配置

# 菜单内的配置说明如下：
# url           链接地址
# name          文本（留空（""）则无）
# weight        权重

[menu]
    # 菜单栏
    [[menu.main]]
        url = "/archives/"
        name = "归档"
        weight = 1
    [[menu.main]]
        url = "https://mirror.raycoder.me/"
        name = "记录"
        weight = 2
    [[menu.main]]
        url = "/links/"
        name = "后♂宫"
        weight = 3
    [[menu.main]]
        url = "/messages/"
        name = "留言板"
        weight = 4
    [[menu.main]]
        url = "/about/"
        name = "关于"
        weight = 5

# Pinned Pages
[[params.pinned]]
    title = "HUGO-THEME-TONY"
    name = "HUGO主题TONY"
    icon = "ri-code-box-line"
    url = "https://htony.js.org/"
[[params.pinned]]
    title = "体系"
    name = "体系"
    icon = "ri-git-branch-line"
    url = "/learn/"
[[params.pinned]]
    title = "标签"
    name = "标签"
    icon = "ri-bookmark-3-line"
    url = "/tags/"
[[params.pinned]]
    title = "分类"
    name = "分类"
    icon = "ri-folder-shield-2-line"
    url = "/categories/"

# Markdown 渲染器
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = false
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = true

# Hugo 的输出控制
[outputs]
    page = ["HTML"]
    home = ["HTML", "SectionsRSS", "SectionsAtom", "Algolia", "BaiduURLs"]
    section = ["HTML"]
    # 类别
    taxonomyTerm = ["HTML"]
    # 类别项
    taxonomy = ["HTML"]
    # 说明：https://github.com/gohugoio/hugo/issues/4528#issuecomment-508488859

# Atom 文件格式的媒体类型
[mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

# Tony 主题自定义的 Atom 模板 来自MemE
[outputFormats.SectionsAtom]
    mediaType = "application/atom+xml"
    baseName = "atom"

# Tony 主题自定义的 RSS 模板 来自MemE
[outputFormats.SectionsRSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

# RSS & Atom 文章数限制
[services.rss]
    limit = -1

##########################################
# 主题配置

[params]

    ######################################
    # 站点信息

    # 站点的 LOGO
    siteLogo = "https://cdn.jsdelivr.net/gh/FFRaycoder/cdn/imgs/20200509175026.png"

    # 站点描述
    siteDescription = "Ray's Blog-夜晚再黑，也压不过雪的白！"

    ######################################
    # 文章分区范围

    # 说明：分区的名字即站点的 content 目录下
    #      的文件夹的名字。

    mainSections = ["status", "p"]

    ######################################
    # 版权保护
    
    # 是否开启
    enableCopyright = true

    copyrightName = "CC BY-NC 4.0"
    copyrightLink = "https://creativecommons.org/licenses/by-nc/4.0/"

    ######################################
    # 目录
    
    # 是否开启（全局设置）
    enableToc = true

    ######################################
    # 阅读进度条
    
    # 是否开启（全局设置）
    enableReadingBar = true

    ######################################
    # 文章上下页
    
    # 是否开启（全局设置）
    enableAdjacentPost = true

    ######################################
    # 是否显示 Hugo 和 Tony 的链接

    displayPoweredBy = true

    ######################################
    # Markdown 相关

    # 在新标签页打开外链？
    hrefTargetBlank = true

    ######################################
    # 评论

    # 是否开启（全局设置）
    enableComments = true
    # 说明：文章的 Front Matter 中的 `comments`
    #      的优先级高于此处

    ## Valine
    enableValine = true
    valineVersion = "latest"
    valineAppId = "e2T8oJJTuQE1A2aE6Wu7wD8p-MdYXbMMI"
    valineAppKey = "CJOMWxWOTPQ8WLGolGAqi6wz"
    valinePlaceholder = "(｡◕ˇ∀ˇ◕)来鸭！快活鸭！"
    valinePath = ""
    valineAvatar = "mm"
    valineMeta = ["nick", "mail", "link"]
    valinePageSize = 15
    valineLang = "zh-cn"
    valineVisitor = true
    valineHighlight = true
    avatarForce = true
    valineRecordIP = true
    valineServerURLs = ""
    valineEmojiCDN = "//cdn.jsdelivr.net/gh/FFRaycoder/cdn@latest/imgs/emoji/"
    valineEmojiMaps = """{"custom/custom_1":"custom/1.webp","custom/custom_2":"custom/2.webp","custom/custom_3":"custom/3.jpg","custom/custom_4":"custom/4.jpg","custom/custom_5":"custom/5.gif","custom/custom_6":"custom/6.gif","custom/custom_7":"custom/7.webp","custom/custom_8":"custom/8.webp","custom/custom_9":"custom/9.webp","custom/custom_10":"custom/10.webp","custom/custom_11":"custom/11.webp","custom/custom_12":"custom/12.webp","custom/custom_13":"custom/13.webp","custom/custom_14":"custom/14.webp","custom/custom_15":"custom/15.gif","custom/custom_16":"custom/16.webp","custom/custom_17":"custom/17.webp","custom/custom_18":"custom/18.jpg","custom/custom_19":"custom/19.webp","custom/custom_20":"custom/20.webp","custom/custom_21":"custom/21.webp","custom/custom_22":"custom/22.webp","custom/custom_23":"custom/23.webp","custom/custom_24":"custom/24.webp","custom/custom_25":"custom/25.jpg","custom/custom_26":"custom/26.webp","custom/custom_27":"custom/27.webp","custom/custom_28":"custom/28.webp","custom/custom_29":"custom/29.webp","custom/custom_30":"custom/30.gif","tv/tv_doge":"tv/tv_doge.gif","tv/tv_亲亲":"tv/tv_亲亲.png","tv/tv_偷笑":"tv/tv_偷笑.png","tv/tv_再见":"tv/tv_再见.png","tv/tv_冷漠":"tv/tv_冷漠.png","tv/tv_发怒":"tv/tv_发怒.png","tv/tv_发财":"tv/tv_发财.png","tv/tv_可爱":"tv/tv_可爱.gif","tv/tv_吐血":"tv/tv_吐血.gif","tv/tv_呆":"tv/tv_呆.png","tv/tv_呕吐":"tv/tv_呕吐.png","tv/tv_困":"tv/tv_困.png","tv/tv_坏笑":"tv/tv_坏笑.gif","tv/tv_大佬":"tv/tv_大佬.gif","tv/tv_大哭":"tv/tv_大哭.png","tv/tv_委屈":"tv/tv_委屈.png","tv/tv_害羞":"tv/tv_害羞.gif","tv/tv_尴尬":"tv/tv_尴尬.gif","tv/tv_微笑":"tv/tv_微笑.png","tv/tv_思考":"tv/tv_思考.png","tv/tv_惊吓":"tv/tv_惊吓.gif","tv/tv_打脸":"tv/tv_打脸.png","tv/tv_抓狂":"tv/tv_抓狂.png","tv/tv_抠鼻":"tv/tv_抠鼻.gif","tv/tv_斜眼笑":"tv/tv_斜眼笑.png","tv/tv_无奈":"tv/tv_无奈.gif","tv/tv_晕":"tv/tv_晕.png","tv/tv_流汗":"tv/tv_流汗.gif","tv/tv_流泪":"tv/tv_流泪.png","tv/tv_流鼻血":"tv/tv_流鼻血.png","tv/tv_点赞":"tv/tv_点赞.gif","tv/tv_生气":"tv/tv_生气.png","tv/tv_生病":"tv/tv_生病.png","tv/tv_疑问":"tv/tv_疑问.png","tv/tv_白眼":"tv/tv_白眼.png","tv/tv_皱眉":"tv/tv_皱眉.png","tv/tv_目瞪口呆":"tv/tv_目瞪口呆.png","tv/tv_睡着":"tv/tv_睡着.png","tv/tv_笑哭":"tv/tv_笑哭.gif","tv/tv_腼腆":"tv/tv_腼腆.gif","tv/tv_色":"tv/tv_色.gif","tv/tv_调侃":"tv/tv_调侃.png","tv/tv_调皮":"tv/tv_调皮.png","tv/tv_鄙视":"tv/tv_鄙视.png","tv/tv_闭嘴":"tv/tv_闭嘴.png","tv/tv_难过":"tv/tv_难过.gif","tv/tv_馋":"tv/tv_馋.png","tv/tv_鬼脸":"tv/tv_鬼脸.png","tv/tv_黑人问号":"tv/tv_黑人问号.gif","tv/tv_鼓掌":"tv/tv_鼓掌.gif","alu/alu_不出所料":"alu/不出所料.png","alu/alu_alu不说话":"alu/不说话.png","alu/alu_不高兴":"alu/不高兴.png","alu/alu_中刀":"alu/中刀.png","alu/alu_中指":"alu/中指.png","alu/alu_中枪":"alu/中枪.png","alu/alu_亲亲":"alu/亲亲.png","alu/alu_便便":"alu/便便.png","alu/alu_内伤":"alu/内伤.png","alu/alu_击掌":"alu/击掌.png","alu/alu_口水":"alu/口水.png","alu/alu_呲牙":"alu/呲牙.png","alu/alu_咽气":"alu/咽气.png","alu/alu_哭泣":"alu/哭泣.png","alu/alu_喜极而泣":"alu/喜极而泣.png","alu/alu_喷水":"alu/喷水.png","alu/alu_喷血":"alu/喷血.png","alu/alu_坐等":"alu/坐等.png","alu/alu_害羞":"alu/害羞.png","alu/alu_小眼睛":"alu/小眼睛.png","alu/alu_尴尬":"alu/尴尬.png","alu/alu_得意":"alu/得意.png","alu/alu_惊喜":"alu/惊喜.png","alu/alu_想一想":"alu/想一想.png","alu/alu_扇耳光":"alu/扇耳光.png","alu/alu_投降":"alu/投降.png","alu/alu_抠鼻":"alu/抠鼻.png","alu/alu_抽烟":"alu/抽烟.png","alu/alu_无奈":"alu/无奈.png","alu/alu_无所谓":"alu/无所谓.png","alu/alu_无语":"alu/无语.png","alu/alu_暗地观察":"alu/暗地观察.png","alu/alu_期待":"alu/期待.png","alu/alu_欢呼":"alu/欢呼.png","alu/alu_汗":"alu/汗.png","alu/alu_深思":"alu/深思.png","alu/alu_狂汗":"alu/狂汗.png","alu/alu_献花":"alu/献花.png","alu/alu_献黄瓜":"alu/献黄瓜.png","alu/alu_皱眉":"alu/皱眉.png","alu/alu_看不见":"alu/看不见.png","alu/alu_看热闹":"alu/看热闹.png","alu/alu_高兴":"alu/高兴.png","alu/alu_黑线":"alu/黑线.png","alu/alu_鼓掌":"alu/鼓掌.png","alu/alu_瞅你":"alu/瞅你.png","alu/alu_肿包":"alu/肿包.png","alu/alu_脸红":"alu/脸红.png","alu/alu_蜡烛":"alu/蜡烛.png","alu/alu_装大款":"alu/装大款.png","alu/alu_观察":"alu/观察.png","alu/alu_赞一个":"alu/赞一个.png","alu/alu_邪恶":"alu/邪恶.png","alu/alu_锁眉":"alu/锁眉.png","alu/alu_长草":"alu/长草.png","alu/alu_阴暗":"alu/阴暗.png","alu/alu_吐":"alu/吐.png","alu/alu_吐舌":"alu/吐舌.png","alu/alu_吐血倒地":"alu/吐血倒地.png","btext/btext_害":"btext/害.png","btext/btext_张三":"btext/张三.png","btext/btext_我全都要":"btext/我全都要.png","btext/btext_我哭了":"btext/我哭了.png","btext/btext_我太南了":"btext/我太南了.png","btext/btext_我裂开了":"btext/我裂开了.png","btext/btext_我酸了":"btext/我酸了.png","btext/btext_打卡":"btext/打卡.png","btext/btext_有内味了":"btext/有内味了.png","btext/btext_有生之年":"btext/有生之年.png","btext/btext_这次一定":"btext/这次一定.png","btext/btext_镇站之宝":"btext/镇站之宝.png","btext/btext_高产":"btext/高产.png","btext/btext_三连":"btext/三连.png","btext/btext_下次一定":"btext/下次一定.png","btext/btext_不愧是你":"btext/不愧是你.png","btext/btext_你币有了":"btext/你币有了.png","btext/btext_危":"btext/危.png","btext/btext_吹爆":"btext/吹爆.png","btext/btext_大师球":"btext/大师球.png","btext/btext_奥力给":"btext/奥力给.png","btext/btext_妙啊":"btext/妙啊.png","btext/btext_完结撒花":"btext/完结撒花.png","btext/btext_爱了爱了":"btext/爱了爱了.png","btext/btext_爷关更":"btext/爷关更.png","btext/btext_狼火":"btext/狼火.png","btext/btext_猛男必看":"btext/猛男必看.png","btext/btext_真香":"btext/真香.png","btext/btext_知识盲区":"btext/知识盲区.png","btext/btext_神仙UP":"btext/神仙UP.png","btext/btext_秀":"btext/秀.png","btext/btext_知识增加":"btext/知识增加.png","btext/btext_标准结局":"btext/标准结局.png","btext/btext_AWSL":"btext/AWSL.png","btext/btext_可以":"btext/可以.png","btext/btext_你细品":"btext/你细品.png"}"""
    valineEnableQQ = false
    valineRequiredFields = ["nick", "mail"]
    # 说明：https://valine.js.org/

    ######################################
    # Google Analytics

    enableGoogleAnalytics = true

    # 跟踪代码的类型
    trackingCodeType = "gtag"
    # 说明：gtag 或 analytics

    trackingID = "UA-157970228-1"

    ######################################
    # Google Site Verification

    googleSiteVerification = ""


    ######################################
    # Baidu推送

    enableBaiduPush = true


[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[outputFormats.BaiduURLs]
    baseName = "baiduurls"
    isPlainText = true
    mediaType = "text/plain"
    notAlternative = true

[params.algolia]
    appId = "LHJ9Z6A43Y"
    indexName = "raycoder.me"
    searchOnlyKey = "e011cd92a1b0a5741251094c7d3c5ee"